Shop 2 create top products section
javadhaditaghi/Nextjs-Collaboration pull request #3
Opened 2024-10-18 09:16 UTC by negarattarian

hello 
I'll hope you be well 
my task is done

2024-10-19 17:32 UTC, javadhaditaghi requested changes
سلام 
یه لطف کن موارد زیر رو اصلاح کن 
1. عکس ها مطابق با فایل فیگما
2. ریویو ها (ستاره ها) نیاز ب تعریف توی فایل json دارن 
3. تایپ ها رو مشخص کن ( بر اساس رویکرد تایپ اسکریپتی)

2024-10-20 18:59 UTC, negarattarian commented
سلام وقت بخیر من اصلاحات بالا انجام دادم 
برای فایل دیتا همون js تایپ در فایل جداگانه در مسیر دیتا تعریف شده 
و همه اقلام کارت در دیتا اورده شد 
با توجه به مشورتی که با استاد داشتم فعلا بردن دیتا در قالب json نیاز نیست

2024-10-22 21:37 UTC, javadhaditaghi requested changes
سلام دوباره 

یه سری موضوعلت غیر از رسپانسیو شدن هست که باید انجام بشه 
این قسمت باید اینتراکتیو باشه یعنی با کلیک روی هر کدوم از این موارد کارد های مرطبط به اون بیاد.
![image](https://github.com/user-attachments/assets/4206d773-19b1-47c6-85f2-935181d66ee2)

رنگ این قسمت رو هم لطف کنید بی رنگ بذارید، دقیقا مثل فایل فیگما 
![image](https://github.com/user-attachments/assets/f0a9d745-9bfa-4a8e-a024-00e755896bc0)

2024-10-26 14:53 UTC, negarattarian commented
سلام وقتتون بخیر 
موارد بالا انجام شد

2024-11-04 10:06 UTC, negarattarian commented
hello 
responsive title of each card
responsive stars and brand

2024-11-07 19:43 UTC, javadhaditaghi commented
مرسی خسته نباشید

2024-11-07 19:43 UTC, merged